import './globals.css';

import { Suspense } from 'react';

import { Box } from '@mui/material';
import type { Metadata } from 'next';

import { GrafanaInstrumentation } from '@/components/instrumentations/Grafana';
import { NavigationDrawer } from '@/components/navigation-drawer';
import { PagesHeader } from '@/components/pages-header';
import { MuiThemeRegistry } from '@/components/theme-registry/MuiThemeRegistry';
import { PlusJakarta } from '@/font';
import { DRAWER_WIDTH } from '@/utils/constants';

export const metadata: Metadata = {
  title: 'Pocket Network Frontend',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={PlusJakarta.className}>
        <MuiThemeRegistry>
          <NavigationDrawer width={DRAWER_WIDTH} />
          <Box sx={{ ml: { sm: `${DRAWER_WIDTH}px` } }}>
            <PagesHeader />
            {children}
          </Box>
        </MuiThemeRegistry>

        <Suspense>
          <GrafanaInstrumentation />
        </Suspense>
      </body>
    </html>
  );
}
