import './globals.css';

import { Box } from '@mui/material';
import type { Metadata } from 'next';
import Script from 'next/script';

import { NavigationDrawer } from '@/components/NavigationDrawer';
import { PagesTop } from '@/components/PagesTop';
import { MuiThemeRegistry } from '@/components/theme-registry/MuiThemeRegistry';
import { PlusJakarta } from '@/font';
import { DRAWER_WIDTH } from '@/utils/constants';

export const metadata: Metadata = {
  title: 'Pocket Network Frontend',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={PlusJakarta.className}>
        <MuiThemeRegistry>
          <NavigationDrawer width={DRAWER_WIDTH} />
          <Box sx={{ ml: { sm: `${DRAWER_WIDTH}px` } }}>
            <PagesTop />
            {children}
          </Box>
        </MuiThemeRegistry>

        <Script src="/scripts/grafana.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
